### ISSUE TITLE
error compiling sprite_benchmark.lpi FPC 2.7.1

### ISSUE THREAD

**Issue by turric4n** [Relfos/TERRA-Engine#3]
Compile Project: Exit code 1, Errors:4, Hints:28
TERRA_FileIO.pas(21,9) Note: Class should have one destructor only
TERRA_Multimedia.pas(443,25) Hint: Parameter "JoyID" not used
TERRA_Multimedia.pas(443,66) Hint: Parameter "uSize" not used
TERRA_Multimedia.pas(449,21) Hint: Parameter "JoyID" not used
TERRA_Multimedia.pas(455,23) Hint: Parameter "JoyID" not used
TERRA_Multimedia.pas(461,27) Hint: Parameter "JoyID" not used
TERRA_Multimedia.pas(467,29) Hint: Parameter "JoyID" not used
TERRA_Multimedia.pas(472,25) Hint: Parameter "Handle" not used
TERRA_Multimedia.pas(472,39) Hint: Parameter "JoyID" not used
TERRA_Multimedia.pas(472,46) Hint: Parameter "uPeriod" not used
TERRA_Multimedia.pas(472,65) Hint: Parameter "bChanged" not used
TERRA_Multimedia.pas(477,27) Hint: Parameter "JoyID" not used
TERRA_Multimedia.pas(477,34) Hint: Parameter "uThreshold" not used
TERRA_Multimedia.pas(482,29) Hint: Parameter "mcierr" not used
TERRA_Multimedia.pas(482,46) Hint: Parameter "pszText" not used
TERRA_Multimedia.pas(482,66) Hint: Parameter "uLength" not used
TERRA_Multimedia.pas(487,25) Hint: Parameter "lpstrCommand" not used
TERRA_Multimedia.pas(487,39) Hint: Parameter "lpstrReturnString" not used
TERRA_Multimedia.pas(487,69) Hint: Parameter "uReturnLength" not used
TERRA_Multimedia.pas(487,94) Hint: Parameter "hWndCallback" not used
TERRA_Multimedia.pas(492,26) Hint: Parameter "pszDevice" not used
TERRA_Multimedia.pas(497,26) Hint: Parameter "mciId" not used
TERRA_Multimedia.pas(497,41) Hint: Parameter "uMessage" not used
TERRA_Multimedia.pas(497,61) Hint: Parameter "dwParam1" not used
TERRA_Multimedia.pas(497,71) Hint: Parameter "dwParam2" not used
TERRA_Multimedia.pas(502,39) Hint: Parameter "dwElementID" not used
TERRA_Multimedia.pas(502,62) Hint: Parameter "lpstrType" not used
TERRA_Multimedia.pas(507,22) Hint: Parameter "pszCommand" not used
TERRA_OS.pas(137,9) Error: Identifier not found "HGLRC"
TERRA_OS.pas(137,14) Error: Error in type definition
TERRA_OS.pas(144,16) Error: Identifier not found "TRect"
TERRA_OS.pas(144,21) Error: Error in type definition
Codetools, Errors:1
TERRA_OS.pas(137,9) Error: identificador no encontrado: HGLRC

**Comment by Relfos** [comment]
Hi, it seems you are not using the master branch, but instead some old version of the engine?
The current version of TERRA_OS does not even have any reference to HGLRC:

https://github.com/Relfos/TERRA-Engine/blob/master/Engine/OS/Windows/TERRA_OS.pas

Also I just checked, the sprite samples compile and run fine in Lazarus, so please just update the code to latest version :)

**Comment by turric4n** [comment]
Thank you Relfos!
