### ISSUE TITLE
TERRA_PACKAGE_WINDOWS.lpk error

### ISSUE THREAD

**Issue by codz01** [Relfos/TERRA-Engine#6]
Hi Relfos .
i tried installing terra package on windows (from master branch), but seems its not ready yet .
i got errors especially if i disable debuging + enable optimization .
it would be nice if you provide a separate working version of terra engine , so we can test your engine.

best regards

**Comment by Relfos** [comment]
Hi, the engine is not supposed to be used separately, you just add the
package to Lazarus and it compiles along with your project.

It should be all working unless there was some mistake / missing file in
commit.
Please list the errors/files so that I can sort the problem

**Comment by codz01** [comment]
ok , i am using fpc 3.0 & lazarus 1.6RC 
i got this error while installing the package :
lazarus.pp(1,1) Fatal: Cannot find TERRA_PACKAGE_WINDOWS used by Lazarus, incompatible ppu=D:\pascal\TERRA-Engine-master\Engine\Units\i386-win32\TERRA_PACKAGE_WINDOWS.ppu, package TERRA_PACKAGE_WINDOWS

**Comment by Relfos** [comment]
Are you compiling for Windows 64 bits or 32?

Also since FPC 3.0 is kinda new, I did not test it properly with it yet,
the engine worked fine in 2.7.2 though, maybe there were some breaking
changes.

**Comment by codz01** [comment]
i am compiling for windows 32bits .
as you said maybe due to fpc 3.0 , this version has alot of changes compared to previous ones

**Comment by Relfos** [comment]
Probably... if you can give it a try with 2.7.2, it might work.
I don't know what exactly changed yet that could cause incompatibilities,
if you want to help with that, I can try upgrading it.

**Comment by codz01** [comment]
really i don't know , maybe you can give it a try by installing fpc3 & laz 1.6 and see your self whats going on . 
terra engine has a gient source code . its not very easy to debug ;-)

**Comment by Relfos** [comment]
I have Lazarus 1.4.4 installed, which seems to be the latest one available
in the oficial site, and I just confirmed that version works fine, I opened
a couple of samples and they compiled and run without problems.
Did you compile 1.6 from source?
Or do you have any link where I can find a pre-compiled version?
Because I use Windows to do most of my development and its not as easy to
compile it on Windows compared to Linux, I have some old .bat files around
it but they probably need some changes.

**Comment by codz01** [comment]
i download it from here : http://sourceforge.net/projects/lazarus/files/Lazarus%20Windows%2032%20bits/Lazarus%201.6RC1/

and here is the announcement
http://forum.lazarus.freepascal.org/index.php/topic,30663.0.html?PHPSESSID=0004e20b10405c8813bb60a7789eefd6

**Comment by Relfos** [comment]
Thanks for the link!

I installed that Lazarus version, opened the Sprite_benchmark win32 demo,
opened the TERRA_win32 package and added it to the project, pressed
compile, no errors.
Run it, it worked fine.

Try that one, you might have tried using a demo that was broken, if thats
the case please tell me which one so I can fix.

**Comment by codz01** [comment]
yes it compiles fine , but what if you disable debug info and enable optimization ? ,  i got error 
the example Sprite_benchmark crashes at startup ,
![error](https://cloud.githubusercontent.com/assets/10813427/11913014/84e58ef0-a656-11e5-848b-f3e572ffaf7c.png)

i'll try to prepare a clean installation ,and try again , i'll tell you if it works 

best regards

**Comment by Relfos** [comment]
Hmm, I was unable to reproduce this error.

Enabling -O3 optimizations in Lazarus plus disabling debug info still runs
fine, no crashes.

It might be caused by other setting that you might have changed from
default values.

**Comment by codz01** [comment]
now it works with laz 1.4.4 and fpc 2.6.4 , but alot of demos are broken (most of 3D , UI) , needs updating . 

there are alot of engines around but.. this one is really looks powerful , excellent work .
i will definitely start learning this engine .

best regards

**Comment by Relfos** [comment]
Yes, the engine got a major redesign in the last months, and because of it
some demos are broken or unfinished.
If there's any specific demo you're interested in, I can try fixing it.

**Comment by codz01** [comment]
thanks , not necessary , maybe i will wait until you provide a stable release .

keep upthe good work .
