### ISSUE TITLE
xmlSaveCompact ?

### ISSUE THREAD

**Issue by PolywickStudio** [Relfos/TERRA-Engine#7]
hi,

I try compile. Missing xmlSaveCompact and XMLNode. 
Please commit.

**Comment by Relfos** [comment]
Hello, the engine was refactored a bit in the last months, what example you
tried to compile so I can check the problem.

**Comment by PolywickStudio** [comment]
Tools\UIEditor.dpr

**Comment by Relfos** [comment]
Thanks!
I've fixed the compilation errors of the UI editor, however this editor is
not finished yet. A previous version already allowed creating widgets and
saving/loading, it seems something got broken.
In the games I've released before using this engine I created the game GUIs
either programatically or using custom formats. However if you're
interested in using this I might give it another look soon.

**Comment by PolywickStudio** [comment]
Can you make it work with XML. 
Anyway, it's already enough..

Just the amount of features is sufficient for now.

**Comment by Relfos** [comment]
The latest commit supports xml loading/saving. But I tried adding a  button
/image and nothing showed up, I need to investigate.

**Comment by PolywickStudio** [comment]
Please take commits from:
https://github.com/PolywickStudio/TERRA-Engine

I added Delphi XE3,10 support.

**Comment by Relfos** [comment]
Thanks, can you submit it via pull request?

**Comment by PolywickStudio** [comment]
Try now please. A pull request...

**Comment by PolywickStudio** [comment]
Great! your engine works with Delphi XE10 !

**Comment by Relfos** [comment]
I accepted it, thanks! :)
